# Generated by Django 5.0.10 on 2024-12-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
    ]
