# Generated by Django 5.0.10 on 2024-12-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
    ]
