# Generated by Django 5.0.10 on 2024-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_hotel_remove_booking_checkin_date_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
