# Generated by Django 5.0.10 on 2024-12-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.room'),
        ),
    ]
